[package]
name = "auto-volatility"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
queues = "1.1.0"
regex = "1.5.4"
